$axure.loadCurrentPage({
  "url":"列表页.html",
  "generationDate":new Date(1415516582616.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e439f96cca184e3ab46b190fcce4c315",
    "type":"Axure:Page",
    "name":"列表页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c5ba75c0ba604ae484643c1910fa1e0d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFF},
{
                  "color":0xFFFFFF},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":20,
              "y":81},
            "size":{
              "width":350,
              "height":950},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"029b8f45744743beb516152a331466c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFF},
{
                      "color":0xFFFFFF},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":20,
                  "y":81},
                "size":{
                  "width":350,
                  "height":950},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u0.png"}},
{
          "id":"48ef57efb4994532a23cf13bb4e84de2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":55,
              "y":93},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f3f045a040407bb50421124198b9cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":55,
                  "y":93},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 详情页",
                      "target":{
                        "targetType":"page",
                        "url":"详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d23cdebaa4294a51b82f6dab4d6f2f7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":91,
              "y":127},
            "size":{
              "width":99,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"099353daf9f64e96b6842a2c19aff128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":127},
                "size":{
                  "width":99,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"985e038116bb40ce9f94f6639c86f41c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":95,
              "y":163},
            "size":{
              "width":76,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f41078f4b69459e87ad7b5f58fbaa33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":95,
                  "y":163},
                "size":{
                  "width":76,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36d8c26877c94560ad72c6a3a848fb87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":163},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6895a731cdc649fbb8a20f99d9af6642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":163},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页/u15.png"}},
{
          "id":"145627a9c2eb4f24ad955e2655fabe5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":30,
              "y":97},
            "size":{
              "width":8,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d4204a456744d8c87977338e3417e07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":30,
                  "y":97},
                "size":{
                  "width":8,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"545dd81d13e84b589b249d573ef354c6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":125},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aef4f6e2f134075983dffe66ac8d5a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":125},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u12.png"}},
{
          "id":"34ba8e19604f46b8a36d2c29bda40b14",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":95,
              "y":178},
            "size":{
              "width":73,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72f915a39f39433aba0750e07526eba0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":95,
                  "y":178},
                "size":{
                  "width":73,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44d0e4a10291449f9c155af6d3cc6eb0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":213},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/列表页/u16_line.png"}},
{
          "id":"21ce74f9f3404549bbf88c84dcd5a6e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":97},
            "size":{
              "width":100,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dadece01c92d4c888e19f1fda5118e1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":97},
                "size":{
                  "width":100,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"26692c4ddafb4ae78dcfca6c9b080dcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":55,
              "y":237},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ba315d1ba0e4840ac42289061d548ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":55,
                  "y":237},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1288d2b327d411fa86ee7774ec85ec2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":91,
              "y":271},
            "size":{
              "width":99,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0813711dce954ae0a097e5800d99b465",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":91,
                  "y":271},
                "size":{
                  "width":99,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c68d45fa6e14a9786d7180549115da8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":95,
              "y":307},
            "size":{
              "width":83,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f1f9d1c267142f5a1ddf8eb8ee7d9a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":95,
                  "y":307},
                "size":{
                  "width":83,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6263dd9d324949eaa08db5d8fc72cc8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":307},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25ee7cf921994f9d86dfacdeddb3b9e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":307},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页/u15.png"}},
{
          "id":"84a769563d924922b0749df7b2c63e45",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":29,
              "y":243},
            "size":{
              "width":8,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23d3a2175d46465faf2624eae3baf8f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":29,
                  "y":243},
                "size":{
                  "width":8,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f590bac0c79480d8fca56562f75a42e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":269},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3defb57c34df4c47b3f2f11fb5e9dab3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":269},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u12.png"}},
{
          "id":"acb959b8fff64d08a2b75410709d3b36",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":95,
              "y":322},
            "size":{
              "width":109,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1738e6a396104f9b929e42c37bd015f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":95,
                  "y":322},
                "size":{
                  "width":109,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3127803d97d45479e97fdd743d7ab03",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":357},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/列表页/u16_line.png"}},
{
          "id":"0422f45b9b544100bee590f21b22f6cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":243},
            "size":{
              "width":100,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e0a27933e8d423da50b907adca47ad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":243},
                "size":{
                  "width":100,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"b7054a2bea084e1e8bd57eaa3657655c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "verticalAlignment":"bottom",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "location":{
              "x":9,
              "y":2},
            "size":{
              "width":800,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"423399a6cb8644c69d6a74cc1bb05451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"bottom",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "location":{
                  "x":9,
                  "y":2},
                "size":{
                  "width":800,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"3f7d2cc5d33f4a3182dd62f90b9aa0e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":14},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75e59c85eb304b2fb80a8e8eca40defb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":14},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fae71151b2040a98434e740951ccd34",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":724,
              "y":14},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"754a2108ea0b498db9e42d823c046a3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":724,
                  "y":14},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u6.png"}},
{
          "id":"344c8e00b6214cd0aa62811f30298ad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":349,
              "y":10},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22a6c7a31ffb4524a621457229edb525",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":349,
                  "y":10},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5958285c60d54b7e80b14a3f70e421e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":14},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9031841edced4cdebb92258300882b73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":14},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"deb5681934cf4d9eaecaaa6ca3987d46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":653,
              "y":14},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bccfe67180cd49deaefad7f094ccb2b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":653,
                  "y":14},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c621f3768e34306aa600e598857e027",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":49},
            "size":{
              "width":150,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"452433e02512460da1fc8a885b5af10c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FFFF},
            "location":{
              "x":310,
              "y":49},
            "size":{
              "width":60,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c28fa27b0a2e41c1a07bb60d0b0ac4f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FFFF},
                "location":{
                  "x":310,
                  "y":49},
                "size":{
                  "width":60,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u49.png"}},
{
          "id":"909113f9db1146b189890ff8e7486d53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":49},
            "size":{
              "width":150,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90e2bc4bdba348a896b4cfdda89ae9c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":49},
                "size":{
                  "width":150,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u51.png"}},
{
          "id":"726ccf716e86406181700e1c6fc5e3d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":81},
            "size":{
              "width":429,
              "height":950},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f6c0cdafd6646068e5164407b749c95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":81},
                "size":{
                  "width":429,
                  "height":950},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/列表页/u53.png"}},
{
          "id":"9a8684336faf454d921dba73a303475a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":643,
              "y":277},
            "size":{
              "width":34,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96ad36f31b3d4f6583c07492242f8bae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":643,
                  "y":277},
                "size":{
                  "width":34,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 mapTip",
                      "objectsToFades":[{
                          "objectPath":["ed26f8c068c547048fd6f9865038f3ce"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 mapTip",
                      "objectsToFades":[{
                          "objectPath":["ed26f8c068c547048fd6f9865038f3ce"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/列表页/u55.png"}},
{
          "id":"f57000f6159c4b01bcb152ffaf336907",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":511,
              "y":380},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc494c6334c4ffd88b8135587f46422",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":511,
                  "y":380},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"929a3c8681154b6dbacd6dbf1526db5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":546,
              "y":1075},
            "size":{
              "width":263,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4406caf1453421eb96b38ec1875deef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":546,
                  "y":1075},
                "size":{
                  "width":263,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb94619b2e4d4517a352919b39ad76e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "location":{
              "x":312,
              "y":970},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf66a6264b9e46c48df16c726280d0b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "location":{
                  "x":312,
                  "y":970},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed26f8c068c547048fd6f9865038f3ce",
          "label":"mapTip",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":560,
              "y":127},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"aa1998f6ad7b4b4587a6c113552505a7",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3cb88d4f0eb54005b118d48a45f14f2d",
                  "label":"",
                  "parentDynamicPanel":"ed26f8c068c547048fd6f9865038f3ce",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":150},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1280864ea0ba4fe9a65af42870d52778",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed26f8c068c547048fd6f9865038f3ce",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":150},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/列表页/u64.png"}},
{
                  "id":"1fd7e713c3854fbb891f6fd3e2062c42",
                  "label":"",
                  "parentDynamicPanel":"ed26f8c068c547048fd6f9865038f3ce",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":10,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97cfb2ee8e3349228e1de7861bda0b03",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed26f8c068c547048fd6f9865038f3ce",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":10,
                          "y":90},
                        "size":{
                          "width":100,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/列表页/u66.png"}},
{
                  "id":"46c169f147d04a14930e2be2cd49ac41",
                  "label":"",
                  "parentDynamicPanel":"ed26f8c068c547048fd6f9865038f3ce",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":20,
                      "y":18},
                    "size":{
                      "width":37,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43ffbd77fdcc48f98ff5e829875e0d58",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed26f8c068c547048fd6f9865038f3ce",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":20,
                          "y":18},
                        "size":{
                          "width":37,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eb3864a6ab404e8181e6aab265acc668",
                  "label":"",
                  "parentDynamicPanel":"ed26f8c068c547048fd6f9865038f3ce",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":50},
                    "size":{
                      "width":127,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe2f699d9bb3428f9bd2d068053ec92f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed26f8c068c547048fd6f9865038f3ce",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":50},
                        "size":{
                          "width":127,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c28549c384a74b3796ee0d88ed088f65",
                  "label":"",
                  "parentDynamicPanel":"ed26f8c068c547048fd6f9865038f3ce",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d5c4b1dafa62413481f814046c997e02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed26f8c068c547048fd6f9865038f3ce",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":10},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 mapTip",
                              "objectsToFades":[{
                                  "objectPath":["ed26f8c068c547048fd6f9865038f3ce"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/列表页/u72.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e8d6eac4a79c4983bcb7ed20d16205bf",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":92},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c5ba75c0ba604ae484643c1910fa1e0d":{
      "scriptId":"u0"},
    "029b8f45744743beb516152a331466c0":{
      "scriptId":"u1"},
    "48ef57efb4994532a23cf13bb4e84de2":{
      "scriptId":"u2"},
    "65f3f045a040407bb50421124198b9cc":{
      "scriptId":"u3"},
    "d23cdebaa4294a51b82f6dab4d6f2f7c":{
      "scriptId":"u4"},
    "099353daf9f64e96b6842a2c19aff128":{
      "scriptId":"u5"},
    "985e038116bb40ce9f94f6639c86f41c":{
      "scriptId":"u6"},
    "5f41078f4b69459e87ad7b5f58fbaa33":{
      "scriptId":"u7"},
    "36d8c26877c94560ad72c6a3a848fb87":{
      "scriptId":"u8"},
    "6895a731cdc649fbb8a20f99d9af6642":{
      "scriptId":"u9"},
    "145627a9c2eb4f24ad955e2655fabe5b":{
      "scriptId":"u10"},
    "2d4204a456744d8c87977338e3417e07":{
      "scriptId":"u11"},
    "545dd81d13e84b589b249d573ef354c6":{
      "scriptId":"u12"},
    "8aef4f6e2f134075983dffe66ac8d5a0":{
      "scriptId":"u13"},
    "34ba8e19604f46b8a36d2c29bda40b14":{
      "scriptId":"u14"},
    "72f915a39f39433aba0750e07526eba0":{
      "scriptId":"u15"},
    "44d0e4a10291449f9c155af6d3cc6eb0":{
      "scriptId":"u16"},
    "21ce74f9f3404549bbf88c84dcd5a6e5":{
      "scriptId":"u17"},
    "dadece01c92d4c888e19f1fda5118e1f":{
      "scriptId":"u18"},
    "26692c4ddafb4ae78dcfca6c9b080dcb":{
      "scriptId":"u19"},
    "8ba315d1ba0e4840ac42289061d548ae":{
      "scriptId":"u20"},
    "f1288d2b327d411fa86ee7774ec85ec2":{
      "scriptId":"u21"},
    "0813711dce954ae0a097e5800d99b465":{
      "scriptId":"u22"},
    "9c68d45fa6e14a9786d7180549115da8":{
      "scriptId":"u23"},
    "8f1f9d1c267142f5a1ddf8eb8ee7d9a2":{
      "scriptId":"u24"},
    "6263dd9d324949eaa08db5d8fc72cc8a":{
      "scriptId":"u25"},
    "25ee7cf921994f9d86dfacdeddb3b9e7":{
      "scriptId":"u26"},
    "84a769563d924922b0749df7b2c63e45":{
      "scriptId":"u27"},
    "23d3a2175d46465faf2624eae3baf8f6":{
      "scriptId":"u28"},
    "0f590bac0c79480d8fca56562f75a42e":{
      "scriptId":"u29"},
    "3defb57c34df4c47b3f2f11fb5e9dab3":{
      "scriptId":"u30"},
    "acb959b8fff64d08a2b75410709d3b36":{
      "scriptId":"u31"},
    "1738e6a396104f9b929e42c37bd015f0":{
      "scriptId":"u32"},
    "b3127803d97d45479e97fdd743d7ab03":{
      "scriptId":"u33"},
    "0422f45b9b544100bee590f21b22f6cb":{
      "scriptId":"u34"},
    "8e0a27933e8d423da50b907adca47ad0":{
      "scriptId":"u35"},
    "b7054a2bea084e1e8bd57eaa3657655c":{
      "scriptId":"u36"},
    "423399a6cb8644c69d6a74cc1bb05451":{
      "scriptId":"u37"},
    "3f7d2cc5d33f4a3182dd62f90b9aa0e4":{
      "scriptId":"u38"},
    "75e59c85eb304b2fb80a8e8eca40defb":{
      "scriptId":"u39"},
    "1fae71151b2040a98434e740951ccd34":{
      "scriptId":"u40"},
    "754a2108ea0b498db9e42d823c046a3e":{
      "scriptId":"u41"},
    "344c8e00b6214cd0aa62811f30298ad0":{
      "scriptId":"u42"},
    "22a6c7a31ffb4524a621457229edb525":{
      "scriptId":"u43"},
    "5958285c60d54b7e80b14a3f70e421e1":{
      "scriptId":"u44"},
    "9031841edced4cdebb92258300882b73":{
      "scriptId":"u45"},
    "deb5681934cf4d9eaecaaa6ca3987d46":{
      "scriptId":"u46"},
    "bccfe67180cd49deaefad7f094ccb2b3":{
      "scriptId":"u47"},
    "3c621f3768e34306aa600e598857e027":{
      "scriptId":"u48"},
    "452433e02512460da1fc8a885b5af10c":{
      "scriptId":"u49"},
    "c28fa27b0a2e41c1a07bb60d0b0ac4f1":{
      "scriptId":"u50"},
    "909113f9db1146b189890ff8e7486d53":{
      "scriptId":"u51"},
    "90e2bc4bdba348a896b4cfdda89ae9c4":{
      "scriptId":"u52"},
    "726ccf716e86406181700e1c6fc5e3d6":{
      "scriptId":"u53"},
    "4f6c0cdafd6646068e5164407b749c95":{
      "scriptId":"u54"},
    "9a8684336faf454d921dba73a303475a":{
      "scriptId":"u55"},
    "96ad36f31b3d4f6583c07492242f8bae":{
      "scriptId":"u56"},
    "f57000f6159c4b01bcb152ffaf336907":{
      "scriptId":"u57"},
    "7cc494c6334c4ffd88b8135587f46422":{
      "scriptId":"u58"},
    "929a3c8681154b6dbacd6dbf1526db5a":{
      "scriptId":"u59"},
    "d4406caf1453421eb96b38ec1875deef":{
      "scriptId":"u60"},
    "fb94619b2e4d4517a352919b39ad76e5":{
      "scriptId":"u61"},
    "cf66a6264b9e46c48df16c726280d0b0":{
      "scriptId":"u62"},
    "ed26f8c068c547048fd6f9865038f3ce":{
      "scriptId":"u63"},
    "3cb88d4f0eb54005b118d48a45f14f2d":{
      "scriptId":"u64"},
    "1280864ea0ba4fe9a65af42870d52778":{
      "scriptId":"u65"},
    "1fd7e713c3854fbb891f6fd3e2062c42":{
      "scriptId":"u66"},
    "97cfb2ee8e3349228e1de7861bda0b03":{
      "scriptId":"u67"},
    "46c169f147d04a14930e2be2cd49ac41":{
      "scriptId":"u68"},
    "43ffbd77fdcc48f98ff5e829875e0d58":{
      "scriptId":"u69"},
    "eb3864a6ab404e8181e6aab265acc668":{
      "scriptId":"u70"},
    "fe2f699d9bb3428f9bd2d068053ec92f":{
      "scriptId":"u71"},
    "c28549c384a74b3796ee0d88ed088f65":{
      "scriptId":"u72"},
    "d5c4b1dafa62413481f814046c997e02":{
      "scriptId":"u73"},
    "e8d6eac4a79c4983bcb7ed20d16205bf":{
      "scriptId":"u74"}}});